setwd("C:/Users/user/Desktop/datascience/power comp data")
powerc<- read.csv(unz('household_power_consumption.zip', "household_power_consumption.txt"), sep = ";")
powerc$Date<- as.Date(powerc$Date, "%d/ %m/ %Y")
powerc$Time<- strptime(powerc$Time, "%H:%M:%S")
powerc2007<- with(powerc, powerc[(Date >= '2007-02-01' & Date <= '2007-02-02'),])
class(powerc2007$Global_active_power)
powerc2007$Global_active_power<- as.numeric(powerc2007$Global_active_power)
png(file="plot1.png", width = 480, height = 480)
hist(powerc2007$Global_active_power, col = "red", main="Global Active Power", breaks = 12, xlab = "Global Active Power (kilowatts)")
dev.off()